# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{metacon}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joseph Wecker"]
  s.date = %q{2011-10-12}
  s.description = %q{Tool with some similarities to puppet but specializing in fast development iteration and continuous deployment. Specifically initially for use with justin.tv / twitch.tv project clusters.}
  s.email = %q{jwecker@justin.tv}
  s.executables = ["metacon-install", "metacon"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".attic/old/.cmd_common",
    ".attic/old/Gemfile",
    ".attic/old/Gemfile.lock",
    ".attic/old/README",
    ".attic/old/Rakefile",
    ".attic/old/build",
    ".attic/old/initialize",
    ".attic/old/rake_help.rb",
    ".attic/old/rebuild",
    ".attic/old/restart",
    ".attic/old/sync",
    ".attic/old/test",
    ".attic/old/update_submodules",
    ".attic/old/workers_help.sh",
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "TODO.md",
    "VERSION",
    "bin/metacon",
    "bin/metacon-install",
    "lib/VERSION",
    "lib/metacon.rb",
    "lib/metacon/cli_helpers.rb",
    "lib/metacon/command.rb",
    "lib/metacon/self_install.rb",
    "notes-dependency-tool.md",
    "notes.rdoc",
    "shelp/metacon.bashrc",
    "test/helper.rb",
    "test/test_metacon.rb"
  ]
  s.homepage = %q{http://github.com/josephwecker/metacon}
  s.licenses = ["MIT"]
  s.post_install_message = %q{

[1;32m[40m--- Please run [1;37mmetacon-install[1;32m to check dependencies & finish the installation --- [0m

}
  s.require_paths = ["lib"]
  s.requirements = ["git, v1.7.4.1 or greater", "rvm, v1.8.2 or greater", "pythonbrew, v1.1 or greater"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Metacontroller for organizing aggregate projects}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<god>, ["~> 0.11.0"])
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<god>, ["~> 0.11.0"])
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<god>, ["~> 0.11.0"])
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

