# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "metacon"
  s.version = "0.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joseph Wecker"]
  s.date = "2011-10-21"
  s.description = "Tool with some similarities to puppet but specializing in fast development iteration and continuous deployment. Specifically initially for use with justin.tv / twitch.tv project clusters."
  s.email = "jwecker@justin.tv"
  s.executables = [".metacon_unwrapped", "metacon", "metacon-installer"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".attic/metacon-install",
    ".attic/old/.cmd_common",
    ".attic/old/Gemfile",
    ".attic/old/Gemfile.lock",
    ".attic/old/README",
    ".attic/old/Rakefile",
    ".attic/old/build",
    ".attic/old/initialize",
    ".attic/old/rake_help.rb",
    ".attic/old/rebuild",
    ".attic/old/restart",
    ".attic/old/sync",
    ".attic/old/test",
    ".attic/old/update_submodules",
    ".attic/old/workers_help.sh",
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "TODO.md",
    "VERSION",
    "bin/.metacon_unwrapped",
    "bin/metacon",
    "bin/metacon-installer",
    "lib/VERSION",
    "lib/metacon.rb",
    "lib/metacon/cli_helpers.rb",
    "lib/metacon/command.rb",
    "lib/metacon/config.rb",
    "lib/metacon/init.rb",
    "lib/metacon/loaders/helpers.rb",
    "lib/metacon/loaders/index.rb",
    "lib/metacon/loaders/rvm.rb",
    "lib/metacon/project.rb",
    "lib/metacon/self_install.rb",
    "lib/metacon/stat.rb",
    "lib/metacon/switch.rb",
    "metacon.gemspec",
    "notes-dependency-tool.md",
    "notes.rdoc",
    "shelp/metacon-installer.sh",
    "shelp/metacon.bashrc",
    "test/helper.rb",
    "test/test_metacon.rb"
  ]
  s.homepage = "http://github.com/josephwecker/metacon"
  s.licenses = ["MIT"]
  s.post_install_message = "\n\n\e[1;32m\e[40m--- You may need to run \e[1;37mmetacon-installer\e[1;32m to check dependencies & finish the installation --- \e[0m\n\n"
  s.require_paths = ["lib"]
  s.requirements = ["git, v1.7.4.1 or greater", "rvm, v1.8.2 or greater", "pythonbrew, v1.1 or greater"]
  s.rubygems_version = "1.8.10"
  s.summary = "Metacontroller for organizing aggregate projects"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<god>, ["~> 0.11.0"])
      s.add_runtime_dependency(%q<highline>, ["~> 1.6.2"])
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<god>, ["~> 0.11.0"])
      s.add_dependency(%q<highline>, ["~> 1.6.2"])
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<god>, ["~> 0.11.0"])
    s.add_dependency(%q<highline>, ["~> 1.6.2"])
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

