#!/usr/bin/env ruby

require 'rubygems'
libdir = File.join(File.dirname(__FILE__), '..', 'lib')
if File.exists?(File.join(libdir,'metacon.rb'))
  $LOAD_PATH.unshift(libdir)
end
require 'metacon'
require 'metacon/self_install'

ci = MetaCon::SelfInstall.new
ci.check_install
